# Generated by Django 4.0.1 on 2022-01-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('createdAT', models.TimeField(auto_now_add=True)),
                ('updatedAt', models.TimeField(auto_now=True)),
            ],
        ),
    ]
